import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import { loadModel } from "./lib/model";

const Home: NextPage = () => {
  const predictByModel = async () => {
    const model = await loadModel();
    const img = document.getElementById("img") as HTMLImageElement;
    const predictions = await model.classify(img);

    console.log("Predictions: ");
    console.log(predictions);
  };

  useEffect(() => {
    predictByModel();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Image
          src="/coffee.jpg"
          alt="coffee"
          id="img"
          width={360}
          height={360}
        />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
