import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import styles from "../styles/Home.module.css";
import { loadMobilenetModel, predictions } from "./lib/mobilenet";

const Home: NextPage = () => {
  const [predictions, setPredictions] = useState<predictions[]>([]);
  const [value, setValue] = useState<string>("");
  const { register, handleSubmit } = useForm();
  const { ref, ...rest } = register("imageFile");

  const onSubmit = () => {
    (async () => {
      const img = document.getElementById("img") as HTMLImageElement;
      if (!img) return;

      const model = await loadMobilenetModel();
      const classifyPredictions = await model.classify(img);
      setPredictions(classifyPredictions);
    })();
  };

  const onChange = (data: { [x: string]: any[] }) => {
    const reader = new FileReader();
    const file = data["imageFile"][0];
    console.log(file);
    reader.onload = (e: ProgressEvent<FileReader>) => {
      const value = e.target!.result;
      if (typeof value != "string") return;
      setValue(value);
    };
    reader.readAsDataURL(file);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form
          onChange={handleSubmit(onChange)}
          onSubmit={handleSubmit(onSubmit)}
        >
          <input {...rest} type="file" ref={ref} />
          <button>分類</button>
        </form>
        {value && (
          <Image src={value} alt="Coffee" id="img" width={324} height={324} />
        )}
        <ul>
          {predictions.map((prediction, index) => (
            <li key={index}>
              {Math.round(prediction.probability * 100)}%:{" "}
              {prediction.className}
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
