import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { loadMobilenetModel, predictions } from "./lib/mobilenet";

const Home: NextPage = () => {
  const [predictions, setPredictions] = useState<predictions[]>([]);

  useEffect(() => {
    (async () => {
      const model = await loadMobilenetModel();

      const img = document.getElementById("img") as HTMLImageElement;
      const classifyPredictions = await model.classify(img);

      setPredictions(classifyPredictions);
    })();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          src="/coffee.jpeg"
          alt="Coffee"
          id="img"
          width={216}
          height={216}
        />
        <ul>
          {predictions.map((prediction, index) => (
            <li key={index}>
              {Math.round(prediction.probability * 100)}%:{" "}
              {prediction.className}
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
